<a href="https://colab.research.google.com/github/jtlai0921/-/blob/master/%E3%80%8C%E3%80%8CNumpy_ipynb%E3%80%8D%E7%9A%84%E5%89%AF%E6%9C%AC%E3%80%8D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

In [ ]:
# 1 axis
[0, 1, 2, 3]  # 4 elements, length is 4

# 2 axes
[[0, 1, 2, 3],
 [4, 5, 6, 7]]  
 # The length of first axis is 2, 
 # the length of second axis is 4

[[0, 1, 2, 3], [4, 5, 6, 7]]

### Create Numpy ndarray

In [ ]:
import numpy as np

# create 1 axis array from 0 to 3 (not included)
x = np.arange(3)

print(x) # [0, 1, 2]
print(type(x))  # <class 'numpy.ndarray'>

# Specify a float data type
y = np.arange(5, dtype='float64')  
print(y) # [0. 1. 2. 3. 4.]

[0 1 2]
<class 'numpy.ndarray'>
[0. 1. 2. 3. 4.]


### Create numpy.ndarray from Python List

In [ ]:
import numpy as np

python_list = [55, 66]

numpy_array = np.array(python_list)

print(python_list, type(python_list)) # [55, 66] <class 'list'>
print(numpy_array, type(numpy_array)) # [55 66] <class 'numpy.ndarray'>

[55, 66] <class 'list'>
[55 66] <class 'numpy.ndarray'>


### Attributes of  ndarray

In [ ]:
# 1D

import numpy as np

x = np.arange(3)
print(x) # [0, 1, 2]

# ndim - number of axes (dimensions)
print(x.ndim)  # 1 dim

# shape - dimensions of the array
print(x.shape)  # (3, )

# size - the total number of elements
print(x.size)  # 3

# dtype - the type of the elements
print(x.dtype)  # int64

[0 1 2]
1
(3,)
3
int64


In [ ]:
# 2D
import numpy as np

x = np.array([[0, 1, 2], [3, 4, 5]])
print(x)
# [[0 1 2]
#  [3 4 5]]

# ndim - number of axes (dimensions)
print(x.ndim)  # 2

# shape - dimensions of the array
print(x.shape)  # (2, 3)

# size - the total number of elements
print(x.size)  # 6

[[0 1 2]
 [3 4 5]]
2
(2, 3)
6


### Numpy Array reshape

In [ ]:
# reshape
x = np.arange(6)
print(x)  # [0 1 2 3 4 5]

# Method 1
new_shape = x.reshape(3, 2)
print(new_shape)
# [[0 1]
#  [2 3]
#  [4 5]]

# Method 2
new_shape = np.reshape(x, (3, 2))    
    
# All in 1 line
y = np.arange(6).reshape(2, 3)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


### Initialize with Value

In [ ]:
# np.zeros: filled with 0
np.zeros(2)  # array([ 0.,  0.,  0.])
np.zeros((2, 3))  
# array([[ 0.,  0.,  0.],                  
#        [ 0.,  0.,  0.]])

# np.ones: filled with 1
np.ones((2,3))  
# array([[ 1.,  1.,  1.],
#        [ 1.,  1.,  1.]])

# np.full: filled with given value
np.full(shape=(2, 3), fill_value=5566)
# array([[5566, 5566, 5566],
#        [5566, 5566, 5566]])

np.random.random((3,3))

array([[0.99560506, 0.33922047, 0.20031045],
       [0.82664041, 0.33273371, 0.1209027 ],
       [0.5791665 , 0.70642018, 0.63932936]])

### Initialize with Random Value

In [ ]:
# uniform distribution: [0, 1)
np.random.random(size=(3))

# Normal distributution
np.random.normal(loc=0.0, scale=1.0, size=(2,2))

# Random integer
np.random.randint(low=1, high=10, size=(2,2))

array([[1, 2],
       [5, 3]])

### Array Index

In [ ]:
import numpy as np

# 1D array
x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])
x[1]   # 1
x[-3]  # 3

# 2D array
x = np.arange(6).reshape(2, 3)  #[[0, 1, 2],
                                # [3, 4, 5]])
x[0, 1]   # 1
x[1, -2]  # 4

4

### Array Slice & Stride

In [ ]:
import numpy as np

# 1D array
x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])
x[1:5]   # [1, 2, 3, 4]
x[1:6]   # x[1:],  [1, 2, 3, 4, 5]
x[:3]    # x[0:3] , [0, 1, 2]
x[1:4:2] # [1, 3]

# 2D array
x = np.arange(6).reshape(2, 3)  #[[0, 1, 2],
                                # [3, 4, 5]])
x[0, 0:2]    #  [0, 1]
x[:, 1:]     # [[1, 2],
             #  [4, 5]]
x[::1, ::2]  # [[0, 2],
             #  [3, 5]]

# reverse
x[:, ::-1] # [[2, 1, 0],
           #  [5, 4, 3]]

array([[2, 1, 0],
       [5, 4, 3]])

### Boolean / Mask Index 

In [ ]:
import numpy as np

x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])
condition = x<4
x[condition] # [0, 1, 2, 3]

x[condition] = 0
x # [0, 0, 0, 0, 4, 5]

# Mask
# original x      # [ 0, 1, 2, 3, 4, 5]
# if <4, assign 0
print(condition)  # [ True  True  True True  False False]
x                 # [ 0,    0,    0,   0,    4,    5]

[ True  True  True  True False False]


array([0, 0, 0, 0, 4, 5])

### Concatenate
Join a sequence of arrays along an existing axis.



In [ ]:
import numpy as np

x = np.array([[0, 1, 2], [3, 4, 5]])
y = np.array([[6, 7, 8]])

np.concatenate((x, y), axis=0)  # [[0, 1, 2],
                                #  [3, 4, 5],
                                #  [6, 7, 8]]

z = [[55], [66]]       
np.concatenate((x, z), axis=1)  # [[0, 1, 2, 55],
                                #  [3, 4, 5, 66]]

array([[ 0,  1,  2, 55],
       [ 3,  4,  5, 66]])

### Basic Operations

In [ ]:
import numpy as np
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5], [6, 7]])

print(a + b)  # array([[4, 6], [8, 10]])
print(a - b)  # array([[-4, -4], [-4, -4]])
print(a * b)  # array([[0, 5], [12, 21]])
print(a / b)  # array([[0, 0.2], [0.3333, 0.42857143]]

print(a - 3)  # array([[-3, -2], [-1, 0]])
print(a * 2)  # array([[0, 2], [4, 6]])

[[ 4  6]
 [ 8 10]]
[[-4 -4]
 [-4 -4]]
[[ 0  5]
 [12 21]]
[[0.         0.2       ]
 [0.33333333 0.42857143]]
[[-3 -2]
 [-1  0]]
[[0 2]
 [4 6]]


### Basic Statistics

In [ ]:
x = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(np.min(x), x.min())
print(np.max(x), x.max())
print(np.mean(x), x.mean())
print(np.std(x), x.std())

0 0
9 9
4.5 4.5
2.8722813232690143 2.8722813232690143


In [ ]:
x = np.arange(10)
print(np.argmax(x,), np.argmin(x))
x

9 0


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reference Answers for Exercises

#### Q1 Create a 1D array with values from 10 to 19 **(Hint: np.arange)**

In [ ]:
# 1
x = np.arange(10, 20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


#### Q2: Reverse a verctor
ex: [0, 1, 2] -> [2, 1, 0]

In [ ]:
# 2
x = np.arange(6)
x = x[::-1]
print(x)

[5 4 3 2 1 0]


#### Q3: Create a 3x3x3 array with random values 
**(Hint: np.random.random or np.random.normal)**

In [ ]:
# 3
x = np.random.random((3, 3, 3))
print(x)

[[[0.03371376 0.31426959 0.58143607]
  [0.99377945 0.54290089 0.4182975 ]
  [0.00349656 0.05777497 0.64547637]]

 [[0.50500915 0.06261595 0.94750808]
  [0.11153347 0.67763259 0.7187007 ]
  [0.08215877 0.44831325 0.34343577]]

 [[0.06264026 0.57037886 0.61003095]
  [0.96903756 0.54220809 0.96700396]
  [0.01244346 0.73310227 0.3932963 ]]]


#### Q4. Create a 5x5 array with random values and find the minimum and maximum 
**(Hint: np.min, np.max)**

In [ ]:
# 4
x = np.random.random((5, 5))
xmin, xmax = np.min(x), np.max(x) # or x.min(), x.max()
print(xmin, xmax)

0.07635247329669614 0.9580964838624587


#### Q5 :Add a border (filled with 0's) around an 3 * 3 matrix with width 1 
**Hint: np.pad**

In [ ]:
# 5
x = np.ones((3, 3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### Q6. Normalize a 3x3 random matrix to 0~1 
**(Hint: (x - x min) / (x max - x min))**

In [ ]:
# 6
x = np.random.random((3, 3))
x2 = (x - np.min(x)) / (np.max(x) - np.min(x))
print(x)
print(x2)

[[0.30286892 0.40711281 0.72201119]
 [0.76900773 0.61865826 0.02056246]
 [0.31957085 0.90641143 0.9185848 ]]
[[0.31436463 0.43044625 0.78110388]
 [0.83343725 0.66601438 0.        ]
 [0.33296319 0.98644425 1.        ]]


#### Q7. Given a 1D array (0 ~ 12), negate all elements which are between 2 and 9.
ex: [2, 3, 4, 10, 11] -> [-2, -3, -4, 10, 11]

In [ ]:
# 7
x = np.arange(2, 12)
x[(2 < x) & (x < 9)] *= -1
print(x)

[ 2 -3 -4 -5 -6 -7 -8  9 10 11]


Q8. Extract from the array [6, 7, 8, 10, 24, 45, 99,100] by the below conditions
 1. which are not divisible by 3 
 2. which are divisible by 5 
 3. which are divisible by 3 and 5

In [ ]:
# 8
x = np.array([6, 7, 8, 10, 24, 45, 99,100])
div3 = x[x%3 != 0]
print(div3)

div5 = x[x%5 == 0]
print(div5)

div15 = x[(x%3 == 0) & (x%5 == 0)]
print(div15)

[  7   8  10 100]
[ 10  45 100]
[45]


#### Q9. Create random vector of size 10 and replace the maximum value by 0
**Hint: np.argmax**

In [ ]:
# 9
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.07219059 0.23914082 0.29964045 0.04506654 0.25506128 0.28271752
 0.24730079 0.63070725 0.24964245 0.        ]


#### Q10. Create a 4x4 matrix and the row values are from 0 to 3

In [ ]:
# 10
x = np.zeros((4, 4))
x += np.arange(4)
print(x)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
